### PR TITLE
396 read previous research

### LINKED ISSUE #396: Read previous research
### Detailed Description

Researching the same thing twice is bad, therefore read through previous research folders in the paf github

### Definition of Done

Done is everything is read through

### Effort Estimate

3

### Testability

_No response_

### Dependencies

Dependant on the paf github

### PR DESCRIPTION
**Pull request by seitzseb**
# Description

Summarize the previous research of the groups from paf22 and paf23

Fixes #396 

## Type of change

- This change  is a documentation update

## Does this PR introduce a breaking change?

No.

## Most important changes

Changes file /doc/research/paf24/general/old_research_overview.md

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (might be obsolete with CI later on)
- [ ] New and existing unit tests pass locally with my changes (might be obsolete with CI later on)

## Summary by CodeRabbit

- **New Features**
	- Introduced a comprehensive overview of past research related to the autonomous vehicle project, enhancing user understanding of foundational methods and advancements.
	- Added detailed sections on Research and Resources, Acting and Control Modules, Planning and Trajectory Generation, State Machine for Decision-Making, and OpenDrive Integration and Navigation Data.

- **Documentation**
	- Updated the `old_research_overview.md` file to include new subsections for better organization and clarity.

### CODE REVIEW

**Review by RoyaLxPole — COMMENTED** [review]
I think the summary gives a good overview of what has already been implemented in which year. 
I have the following question: Why do you only use the links from paf22?
And I have another suggestion: You could also link your summary to Ludwig's work, which provides an overview of the system.

**Comment by seitzseb** [comment]
Alright @RoyaLxPole, this should incorporate the points from your review.
I decided to get rid of the excessive links altogether since the files or rather folder i hinted at are not really hard to find.
Yes you are right, issue #394 might be related to this issue

**Comment by victor-42** [comment]
How come the behavior tree is not mentioned? (I think it's changed by the group PF23, replacing or changing from PF22 state machines)

**Review by RoyaLxPole — APPROVED** [review]
Looks good for me👍

**Pull request merged**
